services:
  jago.system.ui:
    image: ${DOCKER_REGISTRY-}jagosystemui
    container_name: jago.ui
    build:
      context: .
      dockerfile: Jago.System.UI/Dockerfile
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork:

  
